<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net9.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Google.Protobuf" />
    <PackageReference Include="Microsoft.Extensions.Http" />
    <PackageReference Include="System.Net.Http.Json" />
    <PackageReference Include="Grpc.Tools" />
  </ItemGroup>

  <ItemGroup>
    <Protobuf Include="..\Net9Solution.Api\Protos\greet.proto" Link="Protos\greet.proto" />
  </ItemGroup>

</Project>
